config/routes.rb
Rails.application.routes.draw do
  root to: 'races#index'
  get '/auth/:provider/callback' => 'users#new'
  get '/signup' => 'users#new', as: :signup
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  resources :races, only: [:index, :show]

  get '/settings/profile' => 'users#edit', as: :settings

  # NOTE For Let's Encrypt
  get '/.well-known' => redirect('/.well-known')

  resources :users, param: :username, path: '/', only: [:show, :update, :destroy]
  resources :users, only: [:new, :create]

  namespace :api do
    resources :races, only: [:index, :show, :create, :destroy]
    resources :candidates, only: [] do
      resource :vote, only: [:create]
    end
  end

  match '*path' => 'application#render_404', via: :all
end

app/views/shared/_jumbotron.html.haml
.jumbotron
  .container
    .row
      .col-md-5.col-md-offset-1.col-xs-12
        %h1.title VoteRace
        %p.copy Which one would you vote for ?
      .col-md-3.col-md-offset-1.col-xs-8.col-xs-offset-2
        %h2.title Sign in
        = form_tag signin_path, method: :post do
          .form-group
            = text_field_tag :identifier, '', class: 'form-control', placeholder: 'Username or Email'
          .form-group
            = password_field_tag :password, '', class: 'form-control', placeholder: 'Password'
          .form-group
            = submit_tag 'Sign in', class: 'btn btn-success submit-sign-in-button'

app/views/shared/_jumbotron.html.slim
.jumbotron
  .container
    .row
      .col-md-5.col-md-offset-1.col-xs-12
        h1.title VoteRace
        p.copy Which one would you vote for ?
      .col-md-3.col-md-offset-1.col-xs-8.col-xs-offset-2
        h2.title Sign in
        = form_tag signin_path, method: :post do
          .form-group
            = text_field_tag :identifier, '', class: 'form-control', placeholder: 'Username or Email'
          .form-group
            = password_field_tag :password, '', class: 'form-control', placeholder: 'Password'
          .form-group
            = submit_tag 'Sign in', class: 'btn btn-success submit-sign-in-button'

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      - if signed_in?
        .navbar-toggle
          - if current_page?(user_path(current_user.username))
            = link_to logout_path do
              = fa_icon 'sign-out', text: 'Logout'
          - else
            = link_to image_tag(current_user.image_url, class: 'avatar'), user_path(current_user.username)
      - else
        .navbar-toggle.collapsed{:type => 'button', :'data-toggle' => 'collapse', :'data-target' => '#navbar', :'aria-expanded' => 'false', :'aria-controls' => 'navbar'}
          %span.sr-only
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      = link_to image_tag('voterace.jpg'), root_path, class: 'navbar-brand'
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if signed_in?
          %li.dropdown
            = link_to '#', class: 'dropdown-toggle', 'data-toggle': 'dropdown' do
              = image_tag(current_user.image_url, class: 'avatar')
              .caret
            %ul.dropdown-menu
              %li= link_to 'Your profile', user_path(current_user.username)
              %li= link_to 'Settings', settings_path
              %li.divider{role: 'separator'}
              %li
                = link_to logout_path do
                  = fa_icon 'sign-out', text: 'Logout'
        - else
          %li
            = link_to signin_path, class: 'btn', id: 'sign-in-button' do
              = fa_icon 'sign-in', text: 'Sign in'
          %li
            = link_to signup_path, class: 'btn', id: 'sign-up-button' do
              = fa_icon 'sign-in', text: 'Sign up'

app/views/shared/_navbar.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      - if signed_in?
        .navbar-toggle
          - if current_page?(user_path(current_user.username))
            = link_to logout_path do
              = fa_icon 'sign-out', text: 'Logout'
          - else
            = link_to image_tag(current_user.image_url, class: 'avatar'), user_path(current_user.username)
      - else
        .navbar-toggle.collapsed type='button' data-toggle= 'collapse' data-target= '#navbar' aria-expanded= 'false' aria-controls= 'navbar'
          span.sr-only
          span.icon-bar
          span.icon-bar
          span.icon-bar
      = link_to image_tag('voterace.jpg'), root_path, class: 'navbar-brand'
    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if signed_in?
          li.dropdown
            = link_to '#', class: 'dropdown-toggle', 'data-toggle': 'dropdown' do
              = image_tag(current_user.image_url, class: 'avatar')
              .caret
            ul.dropdown-menu
              li= link_to 'Your profile', user_path(current_user.username)
              li= link_to 'Settings', settings_path
              li.divider role= 'separator'
              li
                = link_to logout_path do
                  = fa_icon 'sign-out', text: 'Logout'
        - else
          li
            = link_to signin_path, class: 'btn', id: 'sign-in-button' do
              = fa_icon 'sign-in', text: 'Sign in'
          li
            = link_to signup_path, class: 'btn', id: 'sign-up-button' do
              = fa_icon 'sign-in', text: 'Sign up'

app/views/shared/_race_list.html.haml
.row.race-list
  .col-md-12
    %ol.list-unstyled
      - races.each do |race|
        %li
          .race
            .race-owner
              = link_to image_tag(race.user.image_url, class: 'avatar'), user_path(race.user.username)
              = link_to race.user.username, user_path(race.user.username), class: 'username'
            .race-detail
              %h2.title= link_to race.title, race
              = render partial: 'shared/candidates', locals: {race: race}
      = paginate(races)

app/views/shared/_races.html.haml
= react_component('Races', props: {url: '/api/races.json'})

app/views/shared/_races.html.slim
= react_component('Races', props: {url: '/api/races.json'})